name: Bug Report
description: Report a bug or unexpected behavior
labels: ['bug', 'triage']
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug!
        Please fill out the form below to help us understand and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: When I do X, Y happens instead of Z
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Create a wizard config with...
        2. Render the WizardContainer...
        3. Click on...
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Example
      description: If applicable, provide a minimal code example that demonstrates the issue
      render: tsx
      placeholder: |
        const config = {
          id: 'my-wizard',
          steps: [...]
        };

        <WizardContainer config={config}>
          <AutoStep />
        </WizardContainer>

  - type: input
    id: version
    attributes:
      label: Better Form Version
      placeholder: 0.1.0
    validations:
      required: true

  - type: dropdown
    id: react-version
    attributes:
      label: React Version
      options:
        - React 18
        - React 19
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      options:
        - Next.js (App Router)
        - Next.js (Pages Router)
        - Vite
        - Create React App
        - Remix
        - Other

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem
